site_name: E.R.P. Consultores y Asociados - Documentación



nav:

    - Inicio: 'index.md'

    - Localización Venezuela:
        - Resumen de Funcionalidad: 'lve/index.md'
        - Impresora Fiscal:
            - Características de la Impresión Fiscal: 'lve/fiscal-printer/index.md'
            - Impresora Fiscal VMax 220:
                - Configuración de Impresora Fiscal (VMax 220): 'lve/fiscal-printer/setup-vmax-220.md'
                - Errores comunes Impresora Fiscal VMax 220: 'lve/fiscal-printer/commons-errors-fiscal-printer.md'
                - Generar Reportes Manualmente: 'lve/fiscal-printer/manual-reports.md'
        - Documentación:
            - Codificación Estándar:
                - Producto: 'lve/standard-coding/product/product-coding.md'
    - ADempiere:
        - Migración:
            - Pack In: 'adempiere/migration/packin.md'
        - Procesos Estándar:
            - Versión 3.7.0:
                - Gestión de Ventas:
                    - Cuentas por Cobrar (CxC):
                        - CxC en Dolares: 'adempiere/standard-processes/invoice-customer/foreign-currency/foreign-currency.md'
                - Gestión de Devoluciones: 
                    - Autorización de Devolución a Proveedor desde Recepción con más de una Factura: 'adempiere/standard-processes/returns/invoice-line/invoice-line.md'
                    - Cierre de Autorización de Devolución de Cliente: 'adempiere/standard-processes/returns/customer-return/customer-return.md'
                - Gestión de Materiales: 
                    - Esquema de Descuentos: 'adempiere/standard-processes/material-management/discount-schema/discount-schema.md'
                - Gestión de Retenciones: 
                    - Retención Multimoneda: 'adempiere/standard-processes/withholding-currency/withholding-currency.md/'
            - Versión 3.9.2:
                - Socio del Negocio:
                    - Ciente: 'adempiere/standard-processes/master/business-partner/client/client.md'
                    - Proveedor: 'adempiere/standard-processes/master/business-partner/provider/partner-provider.md'
                    - Empleado: 'adempiere/standard-processes/master/business-partner/employee/employee.md'
                - Gestión de Compras:
                    - Orden de Compra: 'adempiere/standard-processes/purchase-order/direct-order/purchase-order.md'
                    - Documentos por Pagar: 'adempiere/standard-processes/invoice/invoice.md'
                    - Recepción de Productos: 'adempiere/standard-processes/material-receipt/receipt.md'
                - Gestión de Devoluciones:
                    - Devolución de Cliente: 'adempiere/standard-processes/returns/order-return/order-return.md'
                - Gestión de Saldos Pendientes:
                    - Conciliaciones Automáticas: 'adempiere/standard-processes/automatic-conciliations/concept.md'
        - Verticales:
            - Manejo de Préstamos:
                - Requerimientos: 'adempiere/vertical/loan-management/loan-requirements.md'
                - Ejecución de Préstamo: 'adempiere/vertical/loan-management/loan-running.md'
                - Préstamo: 'adempiere/vertical/loan-management/loan.md'
                - Generar Selección de Pagos: 'adempiere/vertical/loan-management/generate-payment-selection.md'
                - Generar Pago: 'adempiere/vertical/loan-management/generate-payment.md'
                - Generar Factura: 'adempiere/vertical/loan-management/generate-invoice.md'
    - Procedimiento Estándar ERP:
        - OpenProject: 'general/procedures/openproject/openproject.md'
        - Acordar una Reunión: 'general/procedures/schedule-a-meeting.md'
        - Documentar una Tarea / Error: 'general/procedures/support-doc.md'
        - Desarrollo de Solicitud: 'general/procedures/customer-review.md'
theme:
  name: null
  custom_dir: 'material/'
  language: 'es'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'img/logo.png'
  feature:
    tabs: false

copyright: 'CC BY-NC-ND 4.0 2012 - 2019 E.R.P Consultores y Asociados'
